language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - pypy3
before_install:
  - sudo apt-get update
  - sudo apt-get install libexiv2-dev libboost-python-dev
install:
  - pip install tox
script:
  - tox
